apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  namespace: rabbit-mq
  name: {{ template "rabbitmq.fullname" . }}
  labels:
    app: {{ template "rabbitmq.fullname" . }}
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - rabbit-mq-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription